<?php
   require("blocks/header.php");
   require("blocks/filter-aside.php");
   require("blocks/nav-line.php");
   require("blocks/products-list.php");
   require("blocks/modal-popup.php");
   require("blocks/arrow-top.php");
   require("blocks/footer.php");
?>
